
Traceback (most recent call last):
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 328, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 435, in read
    self._read_serial(docnames)
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 456, in _read_serial
    self.read_doc(docname)
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/builders/__init__.py", line 512, in read_doc
    publisher.publish()
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/docutils/core.py", line 226, in publish
    self.apply_transforms()
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/docutils/core.py", line 206, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/sphinx/transforms/__init__.py", line 79, in apply_transforms
    super().apply_transforms()
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/docutils/transforms/__init__.py", line 173, in apply_transforms
    transform.apply(**kwargs)
  File "/home/rambap/github/pygaul/.nox/docs/lib/python3.12/site-packages/jupyter_sphinx/execute.py", line 170, in apply
    raise ExtensionError(
sphinx.errors.ExtensionError: Cell raised uncaught exception:
[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpygaul[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgeemap[39;00m [38;5;28;01mimport[39;00m Map
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mee[39;00m
[1;32m      5[0m ee[38;5;241m.[39mInitialize()

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/__init__.py:55[0m
[1;32m     51[0m         [38;5;28;01melse[39;00m:
[1;32m     52[0m             [38;5;28mprint[39m(
[1;32m     53[0m                 [38;5;124m"[39m[38;5;124mPlease restart Jupyter kernel after installation if you encounter any errors when importing geemap.[39m[38;5;124m"[39m
[1;32m     54[0m             )
[0;32m---> 55[0m         [38;5;28;01mraise[39;00m e
[1;32m     57[0m [38;5;28;01mif[39;00m _use_eerepr():
[1;32m     58[0m     [38;5;28;01mimport[39;00m [38;5;21;01meerepr[39;00m

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/__init__.py:45[0m
[1;32m     43[0m [38;5;28;01melse[39;00m:
[1;32m     44[0m     [38;5;28;01mtry[39;00m:
[0;32m---> 45[0m         [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mgeemap[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     46[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[1;32m     47[0m         [38;5;28;01mif[39;00m in_colab_shell():

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/geemap.py:28[0m
[1;32m     26[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mbasemaps[39;00m [38;5;28;01mimport[39;00m get_xyz_dict, xyz_to_leaflet
[1;32m     27[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcommon[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m---> 28[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mconversion[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mee_tile_layers[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     30[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m core

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/conversion.py:23[0m
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcollections[39;00m [38;5;28;01mimport[39;00m deque
[1;32m     21[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpathlib[39;00m [38;5;28;01mimport[39;00m Path
[0;32m---> 23[0m [38;5;28;01mimport[39;00m [38;5;21;01mpkg_resources[39;00m
[1;32m     25[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcommon[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     28[0m [38;5;28;01mdef[39;00m [38;5;21mfind_matching_bracket[39m(lines, start_line_index, start_char_index, matching_char[38;5;241m=[39m[38;5;124m"[39m[38;5;124m{[39m[38;5;124m"[39m):

[0;31mModuleNotFoundError[0m: No module named 'pkg_resources'

[91mExtension error:[39;49;00m
Cell raised uncaught exception:
[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpygaul[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgeemap[39;00m [38;5;28;01mimport[39;00m Map
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mee[39;00m
[1;32m      5[0m ee[38;5;241m.[39mInitialize()

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/__init__.py:55[0m
[1;32m     51[0m         [38;5;28;01melse[39;00m:
[1;32m     52[0m             [38;5;28mprint[39m(
[1;32m     53[0m                 [38;5;124m"[39m[38;5;124mPlease restart Jupyter kernel after installation if you encounter any errors when importing geemap.[39m[38;5;124m"[39m
[1;32m     54[0m             )
[0;32m---> 55[0m         [38;5;28;01mraise[39;00m e
[1;32m     57[0m [38;5;28;01mif[39;00m _use_eerepr():
[1;32m     58[0m     [38;5;28;01mimport[39;00m [38;5;21;01meerepr[39;00m

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/__init__.py:45[0m
[1;32m     43[0m [38;5;28;01melse[39;00m:
[1;32m     44[0m     [38;5;28;01mtry[39;00m:
[0;32m---> 45[0m         [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mgeemap[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     46[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[1;32m     47[0m         [38;5;28;01mif[39;00m in_colab_shell():

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/geemap.py:28[0m
[1;32m     26[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mbasemaps[39;00m [38;5;28;01mimport[39;00m get_xyz_dict, xyz_to_leaflet
[1;32m     27[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcommon[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m---> 28[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mconversion[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mee_tile_layers[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     30[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m core

File [0;32m~/github/pygaul/.nox/docs/lib/python3.12/site-packages/geemap/conversion.py:23[0m
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcollections[39;00m [38;5;28;01mimport[39;00m deque
[1;32m     21[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpathlib[39;00m [38;5;28;01mimport[39;00m Path
[0;32m---> 23[0m [38;5;28;01mimport[39;00m [38;5;21;01mpkg_resources[39;00m
[1;32m     25[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcommon[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     28[0m [38;5;28;01mdef[39;00m [38;5;21mfind_matching_bracket[39m(lines, start_line_index, start_char_index, matching_char[38;5;241m=[39m[38;5;124m"[39m[38;5;124m{[39m[38;5;124m"[39m):

[0;31mModuleNotFoundError[0m: No module named 'pkg_resources'
